# Commands can be found at 
# https://docs.helix-editor.com/configuration.html
theme = 'evolve'

[editor]
line-number = "relative"
idle-timeout = 0
completion-trigger-len = 1
scrolloff = 0

[editor.cursor-shape]
insert = "bar"
# select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
X = "extend_line_above"
D = "delete_char_backward"
"home" = "goto_first_nonwhitespace"
"end" = "extend_to_line_end"
"0" = "extend_to_line_start"
"esc" = "collapse_selection"

# Prefer to just use space+w
C-w = "no_op"

# Tree-sitter aware movements
"C-up" = "expand_selection"
"C-down" = "shrink_selection"
"C-left" = "select_prev_sibling"
"C-right" = "select_next_sibling"

"A-o" = "no_op"
"A-up" = "no_op"
"A-i" = "no_op"
"A-down" = "no_op"
"A-p" = "no_op"
"A-left" = "no_op"
"A-n" = "no_op"
"A-right" = "no_op"

# h, j, k, l don't make much sense with Borne Keyboard
h = "no_op"
j = "no_op"
k = "no_op"
l = "flip_selections"
# Rededundant when I also have easy access to page up/down
C-b = "no_op"
C-f = "no_op"

### GLOBAL GOTO
[keys.normal.g]
# gs replaced by normal "home"
s = "no_op" 
# using normal "end" instead
l = "no_op" 
# gh replaced by normal "0"
h = "no_op"
# Prefer to use number + arrows instead
t = "no_op"
c = "no_op"
b = "no_op"

### LEADER
[keys.normal.space]
"space" = ":w"
# System clipboard used in normal mode
y = "no_op"
Y = "no_op"
p = "no_op"
P = "no_op"
R = "no_op"

### WINDOW
[keys.normal.space.w]
# Swap as I prefer vsplit
f = "goto_file_vsplit" 
F = "goto_file_hsplit" 
# Having o as a nemonic for 'close all except this one' is confusing  given that  :o opens a file
o = "no_op"
Q = "wonly"

# Why use C-key when key is available?
C-o = "no_op"
C-q = "no_op"
C-h = "no_op"
C-j = "no_op"
C-k = "no_op"
C-l = "no_op"
C-w = "no_op"
C-s = "no_op"
C-v = "no_op"
C-t = "no_op"
# Add arrowkey options for the shifted hjkl
"C-left" = "swap_view_left"
"C-down" = "swap_view_down"
"C-up" = "swap_view_up"
"C-right" = "swap_view_right"

# Since h, j, k, l don't make much sense when using the Borne Keyboard
j = "no_op"
k = "no_op"
l = "no_op"
H = "no_op"
J = "no_op"
K = "no_op"
L = "no_op"
# Easier to remember, besides; there is no such thing as :split
h = "hsplit" # replaces s
s = "no_op"
[keys.normal.space.w.n]
h = "hsplit_new"
s = "no_op"
# Why use C-key when key is available?
C-s = "no_op"
C-v = "no_op"

###VIEW
[keys.normal.z]
# Prefer zz
c = "no_op"
# Have arrow keys at my disposal
j = "no_op"
k = "no_op"
# Redundant as they are the same in normal mode
"pageup" = "no_op"
"pagedown" = "no_op"
"space" = "no_op"
"backspace" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-u" = "no_op"
"C-d" = "no_op"
"/" = "no_op"
"?" = "no_op"
"n" = "no_op"
"N" = "no_op"

### STICKY VIEW
[keys.normal.Z]
# Prefer Zz
c = "no_op"
# Have arrow keys at my disposal
j = "no_op"
k = "no_op"
# Redundant as they are the same in normal mode
"pageup" = "no_op"
"pagedown" = "no_op"
"space" = "no_op"
"backspace" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-u" = "no_op"
"C-d" = "no_op"
"/" = "no_op"
"?" = "no_op"
"n" = "no_op"
"N" = "no_op"

### SELECT
[keys.select]
X = "extend_line_above"
# h, j, k, l Not needed when using the Borne Keyboard
h = "no_op"
j = "no_op"
k = "no_op"
l = "flip_selections"
g = { e = ["goto_last_line", "goto_line_end"] }

### FILE PICKER
[editor.file-picker]
hidden = false