[language-server]
ltex-ls = { command = "ltex-ls" }

[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"
procMacro.ignored = { leptos_macro = ["component", "server", "island"] }
# rustfmt.overrideCommand = ["leptosfmt", "--stdin", "--rustfmt"]
diagnostics.disabled = [ "inactive-code" ]

[language-server.rust-analyzer.config.cargo]
features = "all"
loadOutDirsFromCheck = true

[[language]]
name = "markdown"
language-servers = ["ltex-ls", "marksman"]

[[language]]
name = "git-commit"
language-servers = ["ltex-ls"]

[[language]]
name = "svelte"
auto-format = true
roots = ["svelte.config.js"]
language-servers = ["tailwindcss-ls", "svelteserver"]
