#!/bin/bash

# Further explanation and attempts at compliance can be found in ./bash.d/xdg-exports.bash
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# source shell configs
for file in "$XDG_CONFIG_HOME/bash/profile.d/"*?.bash; do
    . "$file"
done
