#!/bin/bash

# Further explanation and attempts at compliance can be found in ./bash.d/xdg-exports.bash
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"


# source shell configs
for file in "$XDG_CONFIG_HOME/bash/bash.d/"*?.bash; do
    . "$file"
done

export HISTFILE="$XDG_STATE_HOME"/bash/history
export HISTSIZE=20000
export EDITOR="nvim"
export VISUAL="nvim"
export WALLPAPER="$HOME/media/wallpapers/fish.jpg"

# Generated with https://scriptim.github.io/bash-prompt-generator/
# user:host [directory] git-branch $ 
PS1=' \[\e[0;38;5;134m\]\u\[\e[0;2m\]:\[\e[0;2m\]\h \[\e[0m\][\[\e[0;1m\]\w\[\e[0m\]]\[\e[0;3m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2) \[\e[0m\]$ \[\e[0m\]'

# TODO: better path
# Personal scripts
export PATH=$PATH:$HOME/.scripts
